### ISSUE TITLE
Tokyo 24 / 7

### ISSUE THREAD

**Issue by FrederikWarburg** [Nanne/pytorch-NetVlad#16]
Hi @Nanne and @saibr 

I'm a bit lost in regards to evaluating on the Tokyo 24 / 7 dataset. It seems that the dataloader provided in this repo seems to load Tokyo TimeMachine instead of Tokyo 24 / 7? When I try to load the tokyo247.mat file provide from https://www.di.ens.fr/willow/research/netvlad/data/netvlad_v100_datasets.tar.gz I think I understand the first elements as seen below

```
import scipy.io
mat = scipy.io.loadmat('/tokyo247.mat')

matStruct = mat['dbStruct'].item()
whichSet = matStruct[0].item()
dbImage = [f[0].item() for f in matStruct[1]]
utmDb = matStruct[2].T
```
However, I don't really understand the remaining part of the dbStruct. E.g. what are my query images? And what are the ground truth for each query image?

Help would really be appreciated. Thank you!

**Comment by Nanne** [comment]
As mentioned in the NetVlad paper:

> Tokyo  24/7  [80] contains  76k  database  images  and  315 query images taken using mobile phone cameras. This is an extremely challenging dataset where the queries were taken at  daytime,  sunset  and  night,  while  the  database  images were only taken at daytime as they originate from GoogleStreet View as described above.

I never properly looked into that dataset, so you're probably better off asking the authors of the NetVlad paper. I do think the .mat file structure is different from the pittsburgh dataset, but once loaded it is essentially a dictionary, so you can manually explore the keys.

**Comment by Nanne** [comment]
I actually found this in some older directory, which I've used to parse the tokyo247.mat. 

`dbStruct = namedtuple('dbStruct', ['whichSet', 
    'dbImage', 'utmDb', 'qImage', 'utmQ', 'numDb', 'numQ',
    'posDistThr', 'posDistSqThr', 'nonTrivPosDistSqThr'])

def parse_dbStruct(path):
    mat = loadmat(path)
    matStruct = mat['dbStruct'].item()

    whichSet = matStruct[0].item()

    dbImage = [f[0].item() for f in matStruct[1]]
    utmDb = matStruct[2].T

    qImage = [f[0].item() for f in matStruct[3]]
    utmQ = matStruct[4].T

    numDb = matStruct[5].item()
    numQ = matStruct[6].item()

    posDistThr = matStruct[7].item()
    posDistSqThr = matStruct[8].item()
    nonTrivPosDistSqThr = matStruct[9].item()

    return dbStruct(whichSet, dbImage, utmDb, qImage, 
            utmQ, numDb, numQ, posDistThr, 
posDistSqThr, nonTrivPosDistSqThr)`

**Comment by emilymiller2k01** [comment]
Hi im trying to find the .mat file in order to format the Tokyo247 dataset and with the code above which I have used to try parse the dataset I get this error: 

`Traceback (most recent call last):
  File "format_tokyo247.py", line 68, in <module>
    mat_struct = loadmat(matlab_struct_file_path)["dbStruct"].item()
  File "lib/python3.10/site-packages/scipy/io/matlab/_mio.py", line 234, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
  File "lib/python3.10/site-packages/scipy/io/matlab/_mio.py", line 74, in mat_reader_factory
    mjv, mnv = _get_matfile_version(byte_stream)
  File "lib/python3.10/site-packages/scipy/io/matlab/_miobase.py", line 253, in _get_matfile_version
    raise ValueError('Unknown mat file type, version {}, {}'.format(*ret))
ValueError: Unknown mat file type, version 83, 113`

am I missing something or using the mat file in the wrong way. 

I a using this git repo to format it: https://github.com/gmberton/VPR-datasets-downloader/blob/main/format_tokyo247.py

**Comment by Nanne** [comment]
Try following the suggestion from here: https://github.com/gmberton/VPR-datasets-downloader/issues/10#issuecomment-2027667913

This issue also doesn't seem to directly relate to this repo, so I will close it.
