### ISSUE TITLE
Questions about alpha in vetvlad.py

### ISSUE THREAD

**Issue by liuhuxian** [Nanne/pytorch-NetVlad#18]
hello! Nanne.
could you please tell me the reference about the method of calculating the self.alpha in vetvlad.py? because I cannot find any clues about this in the original paper.
Thanks!

**Comment by Nanne** [comment]
I dont think they talk about the different versions in the paper, but they have some description in the official repo, as well as code that I used to guide my implementation.

See https://github.com/Relja/netvlad/blob/master/README_more.md#netvlad-versions and https://github.com/Relja/netvlad/search?q=alpha&unscoped_q=alpha

**Comment by key-rnaker** [comment]
hi!
i have a question about alpha too
in the paper, they define the alpha like this
α is computed so that the the ratio of the largest and the second largest soft assignment weight a_k(x_i) is on average equal to 100.

1) what does it mean?
2) in your netvlad.py, you compute alpha like this
```
knn = NearestNeighbors(n_jobs=-1) #TODO faiss?
knn.fit(traindescs)
del traindescs
dsSq = np.square(knn.kneighbors(clsts, 2)[1])
del knn
self.alpha = (-np.log(0.01) / np.mean(dsSq[:,1] - dsSq[:,0])).item()
```

but as i know, the function ```knn.kneighbors``` returns [  neighbor distance array , neighbor index array]
so is ```dsSq``` a neighbor index array of returns?
i think ```dsSq``` should be changed to distance not the index
