### ISSUE TITLE
Why need 7 days to train on a single GPU

### ISSUE THREAD

**Issue by avagreeen** [Nanne/pytorch-NetVlad#2]
The process of caching the negative samples for every 1000 iteration  costed too many time. I dont know what is the problem from my side, could you please share your training details with me? like how much time  cost for your training?

**Comment by Nanne** [comment]
The caching is slow because it caches both the negative and all potential positives (i.e., the entire database) every 1000 iterations. In the paper they start off by caching every 1000 iterations and then reduce this over time, I didn't implement that bit. In the paper they find that caching less frequently seems to harm performance, so you can play around with it, but it could have a negative impact on performance.

A single epoch takes about 1.5 hours for me on a 4 GPU setup on the Pittsburgh30k set. Training with max-pooling should be a lot faster, you could try that as a debugging step.

**Comment by mrgransky** [comment]
A single epoch with `max` pooling took approximately one hour and 10 minutes on the Pittsburgh30k set. It is super slow! 

`CudaDeviceProperties(name='Tesla P100-PCIE-16GB', major=6, minor=0, total_memory=16280MB, multi_processor_count=56)`

**Comment by dinarkino** [comment]
> A single epoch with `max` pooling took approximately one hour and 10 minutes on the Pittsburgh30k set. It is super slow!
> 
> `CudaDeviceProperties(name='Tesla P100-PCIE-16GB', major=6, minor=0, total_memory=16280MB, multi_processor_count=56)`

Could you tell me how many epochs you needed to get the same result as in the paper?

**Comment by Nanne** [comment]
To get the results as mentioned in the README you need about 30 epochs. Given the hard negative mining and the necessary steps for that a single epoch is fairly slow indeed.

**Comment by dinarkino** [comment]
> To get the results as mentioned in the README you need about 30 epochs. Given the hard negative mining and the necessary steps for that a single epoch is fairly slow indeed.

Wow, it's around two days. Thank you for the answer!
