### ISSUE TITLE
Question about checkpoint

### ISSUE THREAD

**Issue by RaymondLmx** [Nanne/pytorch-NetVlad#34]
Is the checkpoint trained by youself closed to 'vd16_pitts30k_conv5_3_vlad_preL2_intra_white.mat', which is posted by the writer of netvlad? 

If not, do you think I can train my model based on your checkpoint that my dataset is constructed by grey-scale image?

Thanks for your reply everytime

**Comment by Nanne** [comment]
The checkpoints are quite different, also because this codebase doesn't do whitening. Which one would be more suited for your task I couldn't say.

Would you mind not using the issues for questions about your own project? Issues should be about technical problems with this codebase, any issues that deviate from this I will close without answer in the future.
