### ISSUE TITLE
Building Cache taking too long

### ISSUE THREAD

**Issue by Nik-V9** [Nanne/pytorch-NetVlad#38]
When I started to train the model after clustering the code starts building the cache and continues to do so for a very long time. I waited for the code to finish building the cache for about 3 hours but yet there is no progress. For the model training, I am utilizing a GCP storage bucket on Google Colab. I also tried the same on a GCP VM instance and got the same issue. 

I was wondering if you know if this is something specific to my hardware or is it a bug in the code? For reference, I am attaching the screenshots of specifications of the colab machine and the code block continuously running.
![Screenshot (121)](https://user-images.githubusercontent.com/56788999/92298458-b6280480-ef66-11ea-913f-db50fca8c3a7.png)
![Screenshot (122)](https://user-images.githubusercontent.com/56788999/92298461-bcb67c00-ef66-11ea-840d-3d3392c93870.png)

**Comment by Nanne** [comment]
I agree that 3 hours seems a bit excessive, one of the reasons I didnt even bother adding progress updates during caching as it really shouldn't take very long.

Not sure how this can be a 'bug in the code' though, as I presume it's doing what it needs to, just at a slow pace. You could try adding some print statements during the caching loop, every 10 iterations or something, to see how its progressing. Alternatively, you could add some finer-grained debug statements, timing how long data loading and the forward pass itself are taking.

My guess would be that it is slow due to I/O, but I'm not very familiar with colab. The caching is by far the fastest part of the whole model though, as its only doing inference and storing of the results.

**Comment by Nik-V9** [comment]
Thanks for responding. I too think the I/O in colab might be the bottleneck. Was thinking the same to implement print statements and observe the time taken for forward pass. I was wondering what would generally be the estimated time for the building of cache on the machine you have used to train the model?

**Comment by Nanne** [comment]
I never really timed it, but its really only doing inference, so it should be fast. Maybe 10-20 minutes on Pittsburgh30k ?

**Comment by Nik-V9** [comment]
Oh, just needed a ballpark figure. Will implement the model on a local machine or a VM instance. Thanks for the response, appreciate it! Btw great implementation of netvlad in PyTorch.
