### ISSUE TITLE
Error with Faiss!

### ISSUE THREAD

**Issue by Fleurrr** [Nanne/pytorch-NetVlad#44]
My python version is 3.8, and I installed faiss-gpu=1.6.1.There‘re something wrong when I  run main.py
"kmeans = faiss.Kmeans(encoder_dim, opt.num_clusters, niter, verbose=False)
TypeError: __init__() takes 3 positional arguments but 4 were given"

Could you please tell me the solution!

**Comment by Nanne** [comment]
Seems like in a newer version they changed `niter` to be an named argument, rather than a positional one: https://github.com/facebookresearch/faiss/blob/c5975cda72981329af97df36b4986ae6f65550e2/faiss/python/__init__.py#L947-L950

Changing that line to `kmeans = faiss.Kmeans(encoder_dim, opt.num_clusters, niter=niter, verbose=False)` should fix this. I've committed this change for now without testing, as I assume it won't break anything for older versions. Can you test this and get back to me with if this fixes it?

**Comment by Fleurrr** [comment]
> Seems like in a newer version they changed `niter` to be an named argument, rather than a positional one: https://github.com/facebookresearch/faiss/blob/c5975cda72981329af97df36b4986ae6f65550e2/faiss/python/__init__.py#L947-L950
> 
> Changing that line to `kmeans = faiss.Kmeans(encoder_dim, opt.num_clusters, niter=niter, verbose=False)` should fix this. I've committed this change for now without testing, as I assume it won't break anything for older versions. Can you test this and get back to me with if this fixes it?

It works! Thank you very much for your help！
