### ISSUE TITLE
About test on other datasets

### ISSUE THREAD

**Issue by bo1234566** [Nanne/pytorch-NetVlad#53]
First ,thanks for the remarkable work.Your work has inspired me a lot.
Now, I want to know whether the model trained on our network can be used to test the Oxford Buildings dataset or Paris Buildings dataset？Or can you give me some hints. looking forward to your reply :)

**Comment by Nanne** [comment]
Thanks. most of the credit for this should go to the authors of the Netvlad paper though, this is just a re-implementation. The features from a model trained with Netvlad should be useful for any retrieval task, especially if it concerns buildings / streetscenes. However, some issues have been found w.r.t. to generalisation (see #8). In other words, I don't know how well it will work for those datasets, but it seems worth trying. Otherwise you might want to try and fine-tune on those sets.
